### ISSUE TITLE
sqlplus: command not found

### ISSUE THREAD

**Issue by WebSamuraiDaisuke** [steveswinsburg/oracle12c-vagrant#3]
After cloning this git and unzip Oracle DBA 12c files into database/, I tried 'vagrant up' and 'vagrant ssh', but I could not launch SQL*PLUS as oracle user. Terminal says

[oracle@localhost ~]$ sqlplus
-bash: sqlplus: command not found

What's wrong with me?

**Comment by steveswinsburg** [comment]
Hi,
How did you launch sqlplus and what was the error?

Cheers
Steve

sent from my mobile

**Comment by WebSamuraiDaisuke** [comment]
Hi,

I have tried to launch sqlplus as below

[oracle@localhost ~]$ sqlplus
-bash: sqlplus: command not found <-- error message

Kind regards,
Daisuke

**Comment by WebSamuraiDaisuke** [comment]
I am using Terminal of OSX.
I reproduce the issue step by step below:

1) vagrant up
2) vagrant ssh
3)[vagrant@localhost ~]$ sudo su - oracle
4)[oracle@localhost ~]$ sqlplus
-bash: sqlplus: command not found <--error mssage here

Kind regards,
Daisuke

**Comment by pltanton** [comment]
My bad. [That](https://github.com/plotnikovanton/ol7-oracle12c-ee-vagrant/commit/c6efde107df13512495fb04547747de821340f09) commit should help

**Comment by WebSamuraiDaisuke** [comment]
@plotnikovanton @steveswinsburg 
I am sure I have done 'git clone https://github.com/plotnikovanton/ol7-oracle12c-ee-vagrant', and download the Oracle Database 12c binaries linuxamd64_12102_database_1of2.zip and linuxamd64_12102_database_2of2.zip from 'http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html' and unzip to database/, but still have same issue. I cannot launch sqlplus.

I reproduce the issue:
1) git clone https://github.com/plotnikovanton/ol7-oracle12c-ee-vagrant
2) Download the Oracle Database 12c binaries linuxamd64_12102_database_1of2.zip and linuxamd64_12102_database_2of2.zip from 'http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html' and unzip to database/
3) vagrant up
4) vagrant ssh
5) [vagrant@localhost ~]$ sudo su - oracle
       Last login: Thu Sep 22 17:27:58 UTC 2016
6) [oracle@localhost ~]$ sqlplus
      -bash: sqlplus: command not found

**Comment by steveswinsburg** [comment]
Does the latest commit in here work? I will run this up again today.

**Comment by pltanton** [comment]
Last commit works for me(it was completely clean setup on machine which newer uses vagrant before). @WebSamuraiDaisuke, could you post your output of provision? Also check that internet is available on VM, may be you need to set a proxy.

**Comment by WebSamuraiDaisuke** [comment]
@steveswinsburg @plotnikovanton 
Attachment file is my output of provision
[MyOutputOfOrovision.txt](https://github.com/steveswinsburg/oracle12c-vagrant/files/488656/MyOutputOfOrovision.txt)

This is all out put of my provision today. I could not login as oracle, too....
What's wrong with me?

**Comment by pltanton** [comment]
```
==> default: No package oracle-rdbms-server-12cR1-preinstall available.
```

Yum can't install this package for you, are you shure about 
your stable internet connection? Try to install it by yourself `sudo yum install oracle-rdbms-server-12cR1-preinstall` and post result, please.
